---
- name: Install MySQL Server
  become: true
  package:
    name: mysql-server
    state: latest
  when: mysql_client_only == false

- name: Install MySQL Client
  become: true
  package:
    name: mysql-client
    state: latest
