- name: Check Terminus Installation
  stat:
    path: "/usr/local/bin/terminus"
  register: terminus_installed

- name: Download Terminus Installer
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar"
    dest: "/tmp/terminus-installer.phar"
  when: terminus_installed.stat.exists == false

- name: Install Terminus
  become: true
  shell: "php terminus-installer.phar install"
  args:
   chdir: /tmp
  when: terminus_installed.stat.exists == false
