---
- name: restart php70-fpm
  become: true
  service:
    name: php7.0-fpm
    state: restarted

- name: restart php71-fpm
  become: true
  service:
    name: php7.1-fpm
    state: restarted

- name: restart php72-fpm
  become: true
  service:
    name: php7.2-fpm
    state: restarted

- name: restart php73-fpm
  become: true
  service:
    name: php7.3-fpm
    state: restarted

- name: restart php74-fpm
  become: true
  service:
    name: php7.4-fpm
    state: restarted
