---
- name: Add PPA
  become: true
  apt_repository: repo='ppa:ondrej/php' state=present

- include: "php70.yml"
  when: php70 == true

- include: "php71.yml"
  when: php70 == true

- include: "php72.yml"
  when: php70 == true

- name: Set Default PHP Version
  become: true
  alternatives:
    name: php
    path: /usr/bin/php{{ php_default_version }}
