---
- name: Add PPA
  become: true
  apt_repository: repo='ppa:ondrej/php' state=present

- include: "php70.yml"
  when: php70 == true

- include: "php71.yml"
  when: php70 == true

- include: "php72.yml"
  when: php70 == true

- name: Set Default PHP Version
  become: true
  shell: "update-alternatives --set php /usr/bin/php{{ php_default_version }}"

#- name: Gather Initial PHP Config
#  shell: 'cat /etc/php/7.1/fpm/conf.d/* | md5sum'
#  register: php_initial_configs
#  changed_when: false
#
#- name: Install additional PHP packages
#  become: true
#  package:
#    name: "{{ item }}"
#    state: latest
#  with_items: "{{ php_packages }}"
#
#- name: Set PHP core conig
#  become: true
#  lineinfile:
#    create: true
#    dest: /etc/php/7.1/mods-available/core.ini
#    insertbefore: BOF
#    line: '; priority=00'
#    regexp: '^; priority=.*'
#
#- name: Set PHP core config values
#  become: true
#  lineinfile:
#    create: true
#    dest: /etc/php/7.1/mods-available/core.ini
#    insertafter: EOF
#    line: "{{ item.key }}={{ item.value }}"
#    regexp: "^{{ item.key }}="
#  with_dict: "{{ php_core_config }}"
#
#- name: Configure PHP Tweaks
#  become: true
#  lineinfile:
#    create: true
#    dest: /etc/php/7.1/mods-available/tweaks.ini
#    insertbefore: BOF
#    line: '; priority=99'
#    regexp: '^; priority=.*'
#
#- name: Set PHP tweaks conig values
#  become: true
#  lineinfile:
#    create: true
#    dest: /etc/php/7.1/mods-available/tweaks.ini
#    insertafter: EOF
#    line: "{{ item.key }}={{ item.value }}"
#    regexp: "^{{ item.key }}="
#  with_dict: "{{ php_tweaks_config }}"
#
#- name: Enable PHP config
#  become: true
#  command: "phpenmod {{ item }}"
#  with_items: "{{ php_modules_enabled }}"
#  changed_when: false
#
#- name: Check for PHP config changes
#  shell: 'cat /etc/php/7.1/fpm/conf.d/* | md5sum'
#  register: php_config_current_configs
#  changed_when: php_config_current_configs.stdout != php_initial_configs.stdout
#  notify: restart php-fpm
