---
- name: Install PHP 7.0
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_70_core }}"

- name: Gather Initial PHP 7.0 Config
  shell: 'cat /etc/php/7.0/fpm/conf.d/* | md5sum'
  register: php_initial_configs
  changed_when: false

- name: Install additional PHP 7.0 packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_70_packages }}"

# TODO: install config files.
- name: Configure PHP 7.0 Core Config
  become: true
  template:
    src: php-fpm.conf.j2
    dest: /etc/apache2/conf-available/php7.1-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache


- name: Check for PHP 7.0 config changes
  shell: 'cat /etc/php/7.0/fpm/conf.d/* | md5sum'
  register: php_config_current_configs
  changed_when: php_config_current_configs.stdout != php_initial_configs.stdout
  notify: restart php70-fpm
