#!/bin/bash

apt-get install -y memcached
cp $BASEDIR/conf/memcached/memcached.conf /etc
service memcached restart

apt-get install -y php5-dev
printf "\n" | pecl install memcache-3.0.8
cp $BASEDIR/conf/php/memcache.ini /etc/php5/mods-available
php5enmod memcache
service php5-fpm restart
