#!/bin/bash

mkdir /var/www/web
write_vhost web 0 80 /var/www/web $BASEDIR/conf/apache2/vhost.tpl
a2ensite web
service apache2 reload

echo 'alias web="cd /var/www/web"' >> ~/.bashrc
source ~/.bashrc
