#!/bin/bash

apt-get update
apt-get install -y default-jre firefox xvfb

mkdir /usr/lib/selenium/
mkdir -p /var/log/selenium/
chmod a+w /var/log/selenium/

cp $BASEDIR/conf/testing/start_selenium.txt /usr/lib/selenium/start.sh
cp $BASEDIR/conf/testing/stop_selenium.txt /usr/lib/selenium/stop.sh
chmod a+x /usr/lib/selenium/start.sh
chmod a+x /usr/lib/selenium/stop.sh

cd /usr/lib/selenium/
curl -O http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
mv selenium-server-standalone-2.47.1.jar selenium-server.jar

cp $BASEDIR/conf/testing/selenium.txt /etc/init.d/selenium
update-rc.d selenium defaults
chmod 755 /etc/init.d/selenium
service selenium start

cp $BASEDIR/conf/testing/xvfb.txt /etc/init.d/xvfb
chmod 755 /etc/init.d/xvfb
update-rc.d xvfb defaults
service xvfb start
