#!/bin/bash

mkdir /usr/lib/solr

# Install Solr.
cd /usr/lib/solr
curl -O http://apache.arvixe.com/lucene/solr/5.3.1/solr-5.3.1.tgz
tar zxvf solr-5.3.1.tgz
rm solr-5.3.1.tgz

# Install config.
cp -R $BASEDIR/conf/solr/drupal /usr/lib/solr/solr-5.3.1/server/solr

# Install service.
cp $BASEDIR/conf/solr/solr.txt /etc/init.d/solr
update-rc.d solr defaults
chmod 755 /etc/init.d/solr
service solr start

# Create core.
cd /usr/lib/solr/solr-5.3.1
bin/solr create -c drupal -d server/solr/drupal
