#!/bin/bash

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

apt-get update

apt-get install -y mongodb-org

printf "\n" | pecl install mongo
cp $BASEDIR/conf/php/mongo.ini /etc/php5/mods-available
php5enmod mongo
service php5-fpm restart
