---

- include: install-nodejs-version.yml
  with_items: "{{ node_versions }}"

- name: Set Default Nodejs Version
  become: true
  alternatives:
    name: node
    link: /usr/local/bin/node
    path: /usr/local/bin/node-{{ node_default_version }}

- name: Set Default NPM Version
  become: true
  alternatives:
    name: npm
    link: /usr/local/bin/npm
    path: /usr/local/bin/npm-{{ node_default_version }}

- name: Set Default NPX Version
  become: true
  alternatives:
    name: npx
    link: /usr/local/bin/npx
    path: /usr/local/bin/npx-{{ node_default_version }}
