- name: Set MongoDB Package Source
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/mongodb-org-4.2.list
    line: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse'
    create: yes

- name: Install MongoDB
  become: true
  package:
    name: mongodb-org
    state: latest
    update_cache: yes
    allow_unauthenticated: yes

- name: Make MongoDB is running
  become: true
  systemd:
    state: started
    name: mongod
