---
- name: Install Apache2
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apache_packages }}"

- name: Configure Apache2 ports
  become: true
  template:
    src: ports.conf.j2
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Enable Apache Modules
  become: true
  file:
    src: "/etc/apache2/mods-available/{{ item }}"
    dest: "/etc/apache2/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache
