---
- name: Install curl
  become: true
  package:
    name: curl
    state: latest

- name: Install gzip
  become: true
  package:
    name: gzip
    state: latest

- name: Install unzip
  become: true
  package:
    name: unzip
    state: latest
